- name: yum and apt with condition
  hosts: all
  tasks: 
  - name: install httpd
    yum: 
      - name: httpd
        state: latest 
    when: ansible_os_family == "RedHat"     #condition
  - name: install apache
    apt:
      - name: apache2
        state: latest
    when: ansible_os_family == "Debian"     #condition