- name: this is my first playbook
  hosts: all
  vars:
    pokemon: "pikachu"
  # vars_files:
  #     - ./var.txt
  # vars_prompt:
  #     name: pokemon
  #     prompt: "what is your name"
  #     private: false
  tasks:
    - name: your fav. pockemon
      debug:
        msg: "{{pokemon}}"
    - name: print hi
      debug:
        msg: "{{pokemon}}"
    - name: local variablegit
      debug:
        msg: "{{pokemon}}"
      vars:
        pokemon: "pichu"