- name: this is my first playbook
  hosts: all
  vars:
    pokemon: "pikachu"
  tasks:
    - name: print hello msg
      debug:
        msg: "{{pokemon}}"
    - name: print hi
      debug:
        msg: "{{pokemon}}"
    - name: local variable
      debug:
        msg: "{{pokemon}}"
      vars:
        pokemon: "pichu"